version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment: 
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_READ_USER: "user"
      INFLUXDB_READ_USER_PASSWORD: "user"
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    networks:
      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: myhostname
    ports:
      - "8125:8125"
      - "8092:8092/udp"
      - "8094:8094"
    depends_on:
      - influxdb
    networks: 
      - monitoring
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    volumes:
        - grafana:/var/lib/grafana
    ports:
        - 3333:3000
    depends_on:
        - telegraf
    networks:
      - monitoring

networks: 
  monitoring:
    driver: bridge

volumes:
  grafana:
