version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    networks:
      - monitoring
    
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8125:8125"
      - "8092:8092/udp"
      - "8094:8094"
    depends_on:
      - influxdb
    networks: 
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    volumes:
        - grafana:/var/lib/grafana
    ports:
        - 3333:3000
    depends_on:
        - telegraf
    networks:
      - monitoring

networks: 
  monitoring:
    driver: bridge

volumes:
  grafana:
